# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  imageName: 'oc_registry'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Trendbrregistry'
        repository: 'v1cs-demo'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
- stage: Scan
  displayName: Trend Micro Artifact Scanner
  jobs:
    - job: Image_Scan
      displayName: Image Scan
      pool:
        vmImage: ubuntu-latest
      variables:
        TMAS_API_KEY: ${{ variables.v1apikey }}
      steps:
      - script: |
          tar --version
          wget https://cli.artifactscan.cloudone.trendmicro.com/tmas-cli/latest/tmas-cli_Linux_x86_64.tar.gz
        displayName: Get Latest Version of TMAS
      - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: '**/tmas-cli_Linux_x86_64.tar.gz'
          destinationFolder: 'tmas-cli'
          cleanDestinationFolder: true
          overwriteExistingFiles: true
      - script: |
          ls -la tmas-cli
          echo $(imageName):$(tag)
          echo $(TMAS_API_KEY)
          ./tmas-cli/tmas scan registry:$(imageName):$(tag) --malwareScan --saveSBOM