# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  imageName: 'oc_registry'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        repository: $(imageName)
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
        architecture: 'x64'
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'
    - task: PythonScript@0
      inputs:
        scriptSource: 'filePath'
        scriptPath: 'SmartcheckScan.py'
        arguments: '--dssc-host "$(SC_Host)" --dssc-user "$(SC_User)"  --dssc-password "$(SC_Pass)" --webhook-teams "$(SC_Teams_Weekhook)" --skip-tls-verify "$(imageName)":"$(tag)"'
