# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  imageName: 'oc_registry'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        repository: $(imageName)
- stage: Scan
  displayName: Trend Micro Artifact Scanner
  jobs:
    - job: Image_Scan
      displayName: Image Scan
      pool:
        vmImage: ubuntu-latest
      steps:
      - script: |
          tar --version
          curl -L -o tmas-cli.tar.gz https://cli.artifactscan.cloudone.trendmicro.com/tmas-cli/latest/tmas-cli_Linux_x86_64.tar.gz
          sudo tar -xzvf ./tmas-cli.tar.gz -C tmas-cli
          ls -la
          chmod +x tmas-cli/tmas
        displayName: Get Latest Version of TMAS
      - script: |
          ./tmas-cli/tmas scan registry:$(imageName):$(tag) --malwareScan --saveSBOM
