name: Trend Vision Artifact Scanner
on: 
  push:
    branches: 
      - master
permissions:
  id-token: write
  contents: read

env:
  IMAGE_NAME: ${{ github.repository }}
  

jobs:
    BuildPushImage:
      runs-on: ubuntu-latest
      environment: DockerRegistry
      steps:
        - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: |
            my-docker-hub-namespace/my-docker-hub-repository
            ghcr.io/${{ github.repository }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    TrendMicroArtifactScan:
      runs-on: ubuntu-latest
      environment: DockerRegistry
      needs: [BuildPushImage]
      steps:
        - name: Trend Cloud One Container Security Scan Action
          uses: trendmicro/cloudone-container-security-github-action@1.0.10
          with:
              # Mandatory
              TMAS_API_KEY: ${{ secrets.API_KEY }}
              REGION: us-east-1
              SBOM: true # Saves SBOM to SBOM.json so you can export it as an artifact later.
              IMAGE: xniapdev/django-app:45 # The image need to be public or the pipeline need to have access to the private image of choice.
              # For each threshold below, select the maximum number of vulnerabilities that are acceptable.
              MAX_TOTAL: 1000
              MAX_CRITICAL: 500
              MAX_HIGH: 500
              MAX_MEDIUM: 500
              MAX_LOW: 500
              MAX_NEGLIGIBLE: 500
              MAX_UNKNOWN: 500
              SCAN_RESULT_ARTIFACT: result.json # Save as an artifact in GitHub to be able to keep the result of the scan.
        - name: 'Upload Scan Result Artifact'
          uses: actions/upload-artifact@v3
          with:
            name: scan-result
            path: result.json
            retention-days: 30
        - name: 'Upload SBOM Artifact'
          uses: actions/upload-artifact@v3
          with:
            name: sbom
            path: SBOM.json
            retention-days: 30
