name: Publish Docker image

on: 
  push:
    branches: 
      - master

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: image/
          push: true
          tags: ghcr.io/user/texlive:latest
